### PR TITLE
Fix peerDependencies - #3

### PR DESCRIPTION
**Pull request by serut**
Fix NPM 7 peerDependencies issue

### CODE REVIEW

**Comment by atlefren** [comment]
Upvote on this. 

It seems like newer npm versions are becoming more strict in depencency versions, so we have to resort to npm i --force when using cesium with webpack 5, or skip stripping of pragmas, neither solution are ideal.

Edit: If anyone else is in the same predicament, I've forked this library and applied the PR: https://www.npmjs.com/package/strip-pragma-loader-fork

**Comment by ggetz** [comment]
Hi all, thanks for bringing this up. 

@serut Before we can take a look at this we'll need a CLA from you. Please send in a [Contributor License Agreement](https://github.com/CesiumGS/cesium/blob/main/CONTRIBUTING.md#contributor-license-agreement-cla) (CLA) and comment back here to let us know to check this!

**Comment by serut** [comment]
Hello @ggetz.
It's done !

**Comment by ggetz** [comment]
Awesome, thanks for addressing this @serut!

**Pull request merged**
